### ISSUE TITLE
slot type not really just a documentation

### ISSUE THREAD

**Issue by zellerin** [nmunro/nmunro.github.io#1]
Hi,

In 2020-12-11-cl-tut-10b-classes1.md, you state "The type option is another hint to programmers...".

What the [CLHS ](http://www.lispworks.com/documentation/HyperSpec/Body/m_defcla.htm) says: 

> The :type slot option specifies that the contents of the slot will always be of the specified data type. [...] The consequences of attempting to store in a slot a value that does not satisfy the type of the slot are undefined.

So be warned, this is not a hint to programmers, it is a promise to the compiler, and if you break that promise, anything can happen.

That being said, for example [sbcl manual](http://www.sbcl.org/manual/#Declarations-as-Assertions) says 
> Types declared using the :type slot option in defclass are asserted if and only if the class was defined in safe code and the slot access location is in safe code as well. This laxness does not pose any internal consistency issues, as the CLOS slot types are not available for the type inferencer, nor do CLOS slot types provide any efficiency benefits. 

so what you observed is what you really get in sbcl outside of safe code:
> (locally (declare (optimize (safety 3)))
     (defclass foo () ((a :initarg :a :type integer)))
     (make-instance 'foo :a 'a))

throws appropriate type error.

**Comment by nmunro** [comment]
Thanks for letting me know, I'll have a play (so I understand it better) and write up a correction 👍

**Comment by nmunro** [comment]
@zellerin Are you satisfied with the presentation of the corrections you have offered?

**Comment by zellerin** [comment]
I do not know who is your audience and so whether it is not too much detail for them compared to the rest of the text, but I have no objections - these are your pages :)

**Comment by nmunro** [comment]
It's more from a credit perspective, but if you're fine with it I may tweak the tone or something a little, but generally keep the content, thanks again!

**Comment by zellerin** [comment]
No credit required :)
