### ISSUE TITLE
Basic classes: "there’s no way to set or get their values"

### ISSUE THREAD

**Issue by vindarel** [nmunro/nmunro.github.io#3]
Hello,

on https://nmunro.github.io/nmunro.github.io/2020/12/11/cl-tut-10b-classes1.html

you say that with slots

> there’s no way to set or get their values

that's misleading and false, because there is `slot-value` (and `with-slots` that you use).

Best,

**Comment by nmunro** [comment]
Hey, thanks for the correction (and for teaching me something), I'll do some testing and get an update put later today. Are you ok with me crediting you in the blog, it's something I like to do, but I appreciate some people aren't comfortable or plain don't want it? :)

**Comment by vindarel** [comment]
It's not much but if you like this, no problem! Best,
